pedestrian:
  DummyRules:
    params:
      name: 'Hihi'
vehicle:
  BrightnessRules:
    params:
      video_images_folder: "data/vehicle_external_data/IMAGES"
      color_intensity_threshold: 60
  

